# Cloudflare Pages Configuration
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_NODE_ENV = "production"

# Environment variables for build (set these in Cloudflare Pages dashboard)
# VITE_API_URL - Your backend API URL
# VITE_APP_NAME - "Se-Embe"