# Wrangler configuration for Cloudflare deployment
name = "se-embe"
compatibility_date = "2024-01-15"

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Pages configuration
pages_build_output_dir = "dist"

# Environment variables for build
[vars]
NODE_ENV = "production"

# Custom domain configuration (uncomment and update when ready)
# [env.production]
# name = "se-embe-prod"
# route = { pattern = "your-domain.com/*", zone_name = "your-domain.com" }

# Development environment
[env.preview]
name = "se-embe-preview"