name = "se-embe-api"
main = "src/index.js"
compatibility_date = "2024-01-15"

# Environment variables (set these in Cloudflare dashboard)
[vars]
NODE_ENV = "production"

# Secrets (set using: wrangler secret put SECRET_NAME)
# MONGO_URI
# JWT_SECRET
# SESSION_SECRET

# Optional: Bind to a custom domain
# [env.production]
# name = "se-embe-api-prod"
# route = { pattern = "api.your-domain.com/*", zone_name = "your-domain.com" }

[env.staging]
name = "se-embe-api-staging"